In [2]:
import torch

# 设置数据类型和设备
dtype = torch.float  # 张量数据类型为浮点型
device = torch.device("cpu")  # 本次计算在 CPU 上进行

# 创建并打印两个随机张量 a 和 b
a = torch.randn(2, 3, device=device, dtype=dtype)  # 创建一个 2x3 的随机张量
b = torch.randn(2, 3, device=device, dtype=dtype)  # 创建另一个 2x3 的随机张量

print("张量 a:")
print(a)

print("张量 b:")
print(b)

# 逐元素相乘并输出结果
print("a 和 b 的逐元素乘积:")
print(a * b)

# 输出张量 a 所有元素的总和
print("张量 a 所有元素的总和:")
print(a.sum())

# 输出张量 a 中第 2 行第 3 列的元素（注意索引从 0 开始）
print("张量 a 第 2 行第 3 列的元素:")
print(a[1, 2])

# 输出张量 a 中的最大值
print("张量 a 中的最大值:")
print(a.max())

张量 a:
tensor([[-0.1460,  0.1569,  0.8439],
        [ 0.9855,  0.1076, -1.4911]])
张量 b:
tensor([[-2.9789, -0.3301, -0.2946],
        [ 1.6393, -0.6379,  2.1643]])
a 和 b 的逐元素乘积:
tensor([[ 0.4350, -0.0518, -0.2486],
        [ 1.6155, -0.0686, -3.2272]])
张量 a 所有元素的总和:
tensor(0.4567)
张量 a 第 2 行第 3 列的元素:
tensor(-1.4911)
张量 a 中的最大值:
tensor(0.9855)


In [ ]:
import torch.nn as nn
import torch.optim as optim

# 定义一个简单的全连接神经网络
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 2)  # 输入层到隐藏层
        self.fc2 = nn.Linear(2, 1)  # 隐藏层到输出层
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))  # ReLU 激活函数
        x = self.fc2(x)
        return x

# 创建网络实例
model = SimpleNN()

# 打印模型结构
print(model)

In [4]:
for index, value in enumerate(['apple', 'banana', 'cherry']):
    print(index, value)
    

0 apple
1 banana
2 cherry
